export default {
  windowEl: window,
  documentEl: document,
  htmlEl: document.documentElement,
  bodyEl: document.body,
  catalog: document?.querySelector('.nav__link-catalog'),
  modal: document?.querySelector('.modals-catalog'),
  checkboxItem: document?.querySelectorAll('.descr-top__item'),
  filtersItem: document?.querySelectorAll('.filters__item'),
  filtersContent: document?.querySelectorAll('.filters__content'),
  filtersTop: document?.querySelectorAll('.filters__top'),
  reset: document?.querySelector('.reset-filters'),
  customSelect: document?.querySelectorAll('.custom-select'),
  catalogPropsLeft: document?.querySelector('.catalog-props__left'),
  productCheckboxesItem: document?.querySelectorAll('.product-checkboxes__item'),
  accordions: document?.querySelectorAll('.accordion'),
  tabsСheckboxes: document?.querySelectorAll('.tabs-content__checkbox'),
  tabs: document?.querySelector('.product-tabs'),
  tabsBtn: document?.querySelectorAll('.product-tabs__btn'),
  tabsContent: document?.querySelectorAll('.product-tabs__content'),
  sliderNavItems: document?.querySelectorAll('.slider-nav__item'),
  productColor: document?.querySelector('.product-description__color'),
  productColorBtns: document?.querySelectorAll('.color__button'),
  stepper: document.querySelectorAll('.stepper'),
  equipmentCheckbox: document.querySelectorAll('.order-equipment__item'),
  orderConfirm: document.querySelector('.order-confirm'),
  inputForm: document.querySelectorAll('.input-form'),
  applicationCheckbox: document.querySelectorAll('.application__item'),
  projectsCheckbox: document.querySelectorAll('.projects-slide__item'),
  shippingCheckbox: document.querySelectorAll('.shipping__checkboxes-item'),
  number: document.querySelectorAll('.static__num'),
  statisticsNum: document.querySelectorAll('.statistics__number'),
  catalogFiltersOpen: document.querySelector('.catalog-mobile-filters'),
  catalogProductLeft: document.querySelector('.catalog-product__left'),

}
